server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    #关闭服务检索
    fetch-registry: false
    #不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
